#!/bin/sh

#SBATCH -A DBS21007
#SBATCH --job-name=ds000228-fmriprep
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000228-fmriprep/.reproman/jobs/local/20220303-230537-a9ae/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000228-fmriprep/.reproman/jobs/local/20220303-230537-a9ae/stderr

#SBATCH --nodes=25
#SBATCH --ntasks=100
#SBATCH --time=48:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000228-fmriprep/.reproman/jobs/local/20220303-230537-a9ae

module load launcher
module load remora
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 99); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun